[project]
name = "functions"
version = "0.1.0"
description = "FastAPI SST POC"
dependencies = ["fastapi", "mangum", "boto3", "sst"]
requires-python = "==3.11.*"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
